"""update comment table

Revision ID: 5fafaa9e5887
Revises: e273f0feb2b9
Create Date: 2020-11-19 18:42:32.950969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fafaa9e5887'
down_revision = 'e273f0feb2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('replied_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['replied_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'replied_id')
    # ### end Alembic commands ###
