"""update admin table

Revision ID: f867eed9b2d3
Revises: 890971f00560
Create Date: 2020-11-21 18:15:14.570391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f867eed9b2d3'
down_revision = '890971f00560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('admin', sa.Column('blog_sub_title', sa.String(length=100), nullable=True))
    op.add_column('admin', sa.Column('blog_title', sa.String(length=60), nullable=True))
    op.add_column('admin', sa.Column('name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'name')
    op.drop_column('admin', 'blog_title')
    op.drop_column('admin', 'blog_sub_title')
    op.drop_column('admin', 'about')
    # ### end Alembic commands ###
